config/routes.rb
# -*- mode:ruby; coding:utf-8 -*-

# Netsphere Financial Front / ネットスフィア経理フロント
# Copyright (C) 2007-2009,2011 HORIKAWA Hisashi. All rights reserved.
#     http://www.nslabs.jp/bside/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


Rails.application.routes.draw do

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest


  # You can have the root of your site routed with "root"
  root 'welcome#index'


  ########################
  # グローバルマスタ

  # アカウント
  resource 'account', controller: "account" do
    match 'sign_in', via:[:get, :post]
    post 'sign_out'

    get 'edit_password'
    post 'update_password'
  end

  # 大域設定
  # コントローラは `GlobalSettingsController` (複数形)
  resource 'global_settings' do
    get 'show_specials'
  end

  # 経理メニュー
  resource 'keiri', controller: "keiri" do
    collection do
      get 'export'
      get 'export_old_gl'

      get 'import_account_titles'
      get 'import_account_titles_log'

      get 'import_gl'
      get 'import_gl_log'

      get 'import_partners'
      get 'import_partners_log'

      get 'import_banks'
    end
  end

  resources 'currencies' do
    collection do
      get 'rate'
    end
  end

  resources 'companies' do
    member do
      get 'gl_fix'
    end
  end

  # 銀行
  resources 'banks' do
    collection do
      get 'list'
      get 'search'
    end
  end
  
  resources 'bank_branches'


  ########################
  # dimensions
  
  # 会計部門
  resources 'divisions' do
    collection do
      get 'search'
      get :select_addable
    end
  end
  
  resources 'control_divisions' do
    collection do
      get 'new_root'
    end
    member do
      get 'edit_root'
    end
  end

  # 次元2
  resources 'dimensions'

  # 勘定科目
  resources 'account_titles' do
    collection do
      get 'list'
      get 'search'
      get 'select_addable'   # ● どんなUI?
    end
  end
  
  resources 'account_title_trees'
  
  # 3. 元帳区分
  resources 'kubuns'

  # 4. 消費税・VAT
  resources 'vats'

  
  ########################
  # 取引先
  
  resources 'partners' do
    collection do
      get 'search'
    end

    member do
      get 'bank_accounts', to: "bank_accounts#list"
      get 'bp_addresses', to: "bp_addresses#list"
    end
  end

  resources 'credit_inquiries'

  resources 'bank_accounts'

  resources 'en_bank_accounts'

  resources 'bp_addresses'

  
  ########################
  # 社員

  resources 'users'

  # 人事メニュー
  resource 'human_resources', controller: "human_resources"

  # 役職
  resources 'worker_positions'

  resources 'qualifications'

  
  ########################
  # 販売

  resources 'our_contacts'

  resources 'our_banks'

  # 販売請求書
  resources 'sales_invoices'

  # 債権管理
  resources 'receivings'

  
  ########################
  # 購買・経費

  resources 'invoices'

  resources 'import_declarations'

  resources 'mat_receivings'

  # 経費精算リポート
  resources 'petty_expenses'

  resources 'petty_pays'

  # 小口精算関係のマスタ
  resources 'petty_groups'

  resources 'petty_payees'

  resources 'petty_cash_advances'

  
  ########################
  # 資材

  resources 'mat_parts'
  

  ########################
  # 資金

  resources 'payment_slips'

  resources 'receiving_slips'

  
  #####################################
  # 予算実績管理

  # 総勘定元帳
  resource 'general_ledger', controller: "general_ledger" do
    collection do
      get 'select_ledger'
    end
  end

  resources 'reports'


  #####################################
  # 添付ファイル

  resources 'attach_kinds'

  resources 'attach_files'

  
  #####################################
  # データ連携

  resource 'sbo', controller: "sbo" do
    collection do
      get 'export_bp_master'
      get 'export_bp_master_log'
    end
  end

  resource 'taisho', controller: "taisho"

end

app/controllers/mat_receivings_controller.rb
# -*- coding: utf-8 -*-

# Netsphere Financial Front / ネットスフィア経理フロント
# Copyright (C) 2007-2009,2011 HORIKAWA Hisashi. All rights reserved.
#     http://www.nslabs.jp/bside/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# 材料仕入
class MatReceivingsController < ApplicationController
  before_filter :login_required
  before_filter :role_keiri_required, :only => [:update]

  
  # GET /mat_receivings
  # GET /mat_receivings.xml
  def index
    @mat_receivings = MatReceiving.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @mat_receivings }
    end
  end

  # GET /mat_receivings/1
  # GET /mat_receivings/1.xml
  def show
    @mat_receiving = MatReceiving.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @mat_receiving }
    end
  end

  # GET /mat_receivings/new
  # GET /mat_receivings/new.xml
  def new
    @mat_receiving = MatReceiving.new
  end


  # 特定のフィールドだけ, 編集可能
  # GET /mat_receivings/1/edit
  def edit
    @invoice = Invoice.find params[:invoice]
    @mat_receiving = MatReceiving.find(params[:id])
  end


  # POST /mat_receivings
  # POST /mat_receivings.xml
  def create
    @mat_receiving = MatReceiving.new(params[:mat_receiving])

    respond_to do |format|
      if @mat_receiving.save
        format.html { redirect_to(@mat_receiving, :notice => 'Mat receiving was successfully created.') }
        format.xml  { render :xml => @mat_receiving, :status => :created, :location => @mat_receiving }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @mat_receiving.errors, :status => :unprocessable_entity }
      end
    end
  end


  # PUT /mat_receivings/1
  # PUT /mat_receivings/1.xml
  def update
    @mat_receiving = MatReceiving.find(params[:id])
    @invoice = @mat_receiving.invoice

    # 転送前の分を一度に更新する
    begin
      MatReceiving.transaction do
        @mat_receiving.fixed_asset_flag = params[:mat_receiving][:fixed_asset_flag]
        @mat_receiving.save!
        
        # デフォルト値も更新
        part = @mat_receiving.part
        part.mat_type = params[:part][:mat_type]
        part.mat_class = @mat_receiving.part_mat_class
        part.fixed_asset_flag = @mat_receiving.fixed_asset_flag
        part.save!
      
        mats = MatReceiving.joins("LEFT JOIN invoices ON mat_receivings.invoice_id = invoices.id") \
                .where("(invoices.state < 20 AND invoices.payment_state < 20) AND mat_receivings.part_no = ?", part.part_no) \
                .select("mat_receivings.*")
        mats.each do |mat|
          mat.fixed_asset_flag = part.fixed_asset_flag
          mat.save!
        end
      end
    rescue ActiveRecord::RecordInvalid => e
      @error = e
      render :action => "edit"
      return
    end

    redirect_to( {:controller => "invoices", :action => "show", 
                    :id => @mat_receiving.invoice},
                   :notice => 'Mat receiving was successfully updated.' )
  end


  # DELETE /mat_receivings/1
  # DELETE /mat_receivings/1.xml
  def destroy
    @mat_receiving = MatReceiving.find(params[:id])
    @mat_receiving.destroy

    respond_to do |format|
      format.html { redirect_to(mat_receivings_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/mat_receivings/_form.html.erb
<% # @param @mat_receiving 編集する材料仕入
  %>

<% if @error %>
<div id="errorExplanation">
  <%= @error.inspect %>
</div>
<% end %>



  <%= error_messages_for 'mat_receiving' %>


<p>■材料仕入
<table>
  <tr><th align="right">booking type:<td><%= @mat_receiving.booking_type %>
  <tr><th align="right">order type:<td><%= @mat_receiving.order_type %>
  <tr><th align="right">order no:<td><%= @mat_receiving.order_no %>

  <tr><th align="right">part serial: <td><%= @mat_receiving.part_serial %>
  <tr><th align="right">delivery date:<td><%= @mat_receiving.delivery_date %>
  <tr><th align="right">receiving no:<td><%= @mat_receiving.receiving_no %>
  <tr><th align="right">quantity:<td><%= @mat_receiving.quantity %>
  <tr><th align="right">amount:<td><%= @mat_receiving.total_amount %>
  <tr><th align="right">tax code:<td><%= @mat_receiving.tax_code %>
  <tr><th align="right">tax amount:<td><%= @mat_receiving.tax_amount %>
  <tr><th align="right">charge:<td><%= @mat_receiving.amount_of_charges %>
</table>


<div class="well">
  <h3>■Part</h3>
<% @part = @mat_receiving.part || MatPart.new %>

<table>
  <tr><th align="right">part no:<td><%= @part.part_no %>
  <tr><th align="right">desc.:<td><%= @part.description %>
  <tr><th align="right">mat. type:
    <td>
<% MatPart::MAT_TYPES.each do |code, name| %>
      <label><%= radio_button :part, :mat_type, code %> <%= name %></label>
<% end %>

  <tr><th align="right">mat. class:<td><%= @mat_receiving.part_mat_class %>
  <tr><th align="right">fixed asset?:
    <td><label><%= f.radio_button :fixed_asset_flag, true %> Fixed Asset</label>
      <label><%= f.radio_button :fixed_asset_flag, false %> Non-FA</label>
</table>

  <div class="actions">
    <%= f.submit %>
  </div>
</div>

app/views/mat_receivings/edit.html.erb
<h1>Partの編集</h1>

<%= form_for(@mat_receiving, 
             :url => {:action => "update", :id => @mat_receiving}) do |f| %>

  <%= render :partial => 'form', :locals => {:f => f} %>

<p><%= link_to 'キャンセル', :controller => "invoices", :action => "show", 
                           :id => @invoice %>

<% end %>
  

app/views/mat_receivings/index.html.erb
<h1>Listing mat_receivings</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mat_receivings.each do |mat_receiving| %>
  <tr>
    <td><%= link_to 'Show', :action => 'show', :id => mat_receiving %></td>
    <td><%= link_to 'Edit', :action => 'edit', :id => mat_receiving %></td>

    <td><%= link_to 'Destroy', {:action => 'destroy', :id => mat_receiving}, 
                               :data => {:confirm => 'Are you sure?'},
                               :method => :delete %></td>
  </tr>
<% end %>
</table>

<p><%= link_to 'New Mat receiving', :action => "new" %>

app/views/mat_receivings/new.html.erb
<h1>New mat_receiving</h1>

<%= form_for(@mat_receiving, :url => {:action => "create"}) do |f| %>

  <%= render :partial => 'form', :locals => {:f => f} %>

<p><%= link_to 'キャンセル', :action => "index" %>
<% end %>

app/views/mat_receivings/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_mat_receiving_path(@mat_receiving) %> |
<%= link_to 'Back', mat_receivings_path %>